keywords/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<keyword_id>[0-9]+)/$', views.keyword_detail, name='keyword-detail'),
    url(r'^crawl/$', views.crawl, name='crawl'),
    url(r'^crawl/results/$', views.results, name='results'),
]

keywords/models.py
from django.db import models
from django.utils.timezone import now

class Keyword(models.Model):
    name = models.CharField(max_length=200, unique=True)
    average_count = models.PositiveIntegerField(default=0)
    average_density = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    date_created = models.DateTimeField(auto_now_add=True)
    last_activity = models.DateTimeField(default=now)
    
    def __str__(self):
        return u"%s" % (self.name)

    class Meta:
        ordering = ("name", )


class Result(models.Model):
    url = models.URLField(max_length=200)
    keyword = models.ForeignKey("keywords.Keyword")
    title = models.CharField(max_length=200, blank=True)
    word_count = models.PositiveIntegerField()
    density = models.DecimalField(max_digits=5, decimal_places=2)
    date_created = models.DateTimeField(auto_now_add=True)
    last_activity = models.DateTimeField(default=now)

    def __str__(self):
        return u"%s" % (self.url)
    
    class Meta:
        ordering = ("keyword", "-word_count", "url", )
        unique_together = ("url", "keyword")

keywords/forms.py
from django import forms
from django.template.defaultfilters import striptags


class CrawlForm(forms.Form):
    url = forms.URLField()
    keyword = forms.CharField()


    def clean_keyword(self):
        keyword = self.cleaned_data['keyword']
        if striptags(keyword) != keyword:
            raise forms.ValidationError("You have some HTML code in there.")
        elif "()" in keyword or ";" in keyword:
            raise forms.ValidationError("You have code in there.")
        return keyword

keywords/views.py
from django.shortcuts import render, redirect

from .models import Keyword, Result
from .forms import CrawlForm
from .util import get_page, save_results


def index(request):
    return render(request, 'keywords/index.html')

def keyword_detail(request, keyword_id):
    keyword = Keyword.objects.filter(pk=keyword_id).first()
    other_keywords = Keyword.objects.exclude(pk=keyword_id)
    context = {'keyword': keyword, 'other_keywords': other_keywords, }
    return render(request, 'keywords/keyword-detail.html', context)

def crawl(request):
    if request.method == 'POST':
        form = CrawlForm(request.POST)
        
        if form.is_valid():
            cd = form.cleaned_data
            
            page, error = get_page(cd["url"])
            if error:
                return render(request, 'keywords/crawl.html', dict(
                    form=form, error=error
                ))
            else:
                result = save_results(request, cd, page)
                
            return redirect('results')
    else:
        form = CrawlForm()
    return render(request, 'keywords/crawl.html', {'form': form})

def results(request):
    result_id = request.session.get("result_id")
    
    try:
        result = Result.objects.get(pk=result_id)
    except:
        context=dict(error="No result found.")
        return render(request, 'keywords/results.html', context)
    
    keyword = result.keyword
    allresults = Result.objects.filter(
        keyword=keyword,
        word_count__gt=0
    )
    context = {"result": result, "keyword": keyword, "allresults": allresults }
    return render(request, 'keywords/results.html', context)

keywords/templates/keywords/base.html
{% load staticfiles %}

<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Crawl Assignment{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'keywords/styles.css' %}">
  </head>
  <body>
    <div id="main-container">
      <div id="main-content">
        <div id="top-nav">
          <ul>
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'crawl' %}">Crawl</a></li>
          </ul>
        </div>
        {% block content %}{% endblock %}
      </div>
      <div id="footer-area">
        <p>A test page for crawling. &copy; Trevor Sherk</p>
      </div>
    </div>
  </body>
</html>

keywords/templates/keywords/crawl.html
{% extends "keywords/base.html" %}

{% load keyword_tags %}

{% block title %}Crawl form{% endblock %}

{% block content %}
<h1>Crawl page</h1>

<div id="crawl-form">
  <form method="post" action="">
    {% csrf_token %}
    {% if form.errors %}
    <div class="errorbox">
      <span>Please correct the error{{ form.errors|pluralize }} below:</span>
    </div>
    {% endif %}
    {% if error %}
      <p>There was an error. {{ error }}</p>
    {% endif %}
    <label for="id_url">Link</label> <input id="id_url" name="url" value="{{ request.POST.url }}">
    <span>{{ form.url.errors }}</span>
    <br>
    <label for="id_keyword">Keyword</label> <input id="id_keyword" name="keyword" value="{{ request.POST.keyword }}">
    <span>{{ form.keyword.errors }}</span>
    <br>
    
    <button type="submit" class="btn">Submit</button>
  </form>
</div>
{% if request.session.result_id %}
  {% get_result request.session.result_id as result %}
  {% if result %}
  <div id="previous-search-info">
    <p>By the way, here's what your last successful search term was:</p>
    <ul>
      <li><span>Link:</span>{{ result.url }}</li>
      <li><span>Keyword:</span>{{ result.keyword }}</li>
      <li><span>Count:</span>{{ result.word_count }}</li>
      <li><span>Density:</span>{{ result.density }}%</li>
    </ul>
  </div>
  {% endif %}
{% endif %}
{% endblock %}

keywords/templates/keywords/index.html
{% extends "keywords/base.html" %}

{% block content %}
<h1>Home page</h1>
<p>Go to crawl page: <a href="{% url 'crawl' %}">Crawl page</a></p>
{% endblock %}

keywords/templates/keywords/keyword-detail.html
{% extends "keywords/base.html" %}

{% block content %}
<h1>Keyword detail page</h1>
{% if keyword %}
<p><span class="bolder">Keyword:</span> {{ keyword.name }}</p>
<p><span class="bolder">Average word count:</span> {{ keyword.average_count }}</p>
</p><span class="bolder">Average density:</span> {{ keyword.average_density }}</p>
{% else %}
Sorry, that keyword doesn't exist (anymore).
{% endif %}
<h2>Other keywords</h2>
{% for keyword in other_keywords %}
<a href="{% url 'keyword-detail' keyword.pk %}">{{ keyword.name }}</a><br>
{% endfor %}
{% endblock %}

keywords/templates/keywords/results.html
{% extends "keywords/base.html" %}

{% block title %}Results{% endblock %}

{% block content %}
<h1>Results:</h1>
{% if result %}
<p><span class="bolder">URL</span>: {{ result.url }} <a href="{{ result.url }}" target="_blank">(open)</a></p>
<p><span class="bolder">Title:</span> {{ result.title }}</p>
<p><span class="bolder">Keyword:</span> {{ keyword.name }}</p>
<p><span class="bolder">Keyword count:</span> {{ result.word_count }}</p>
<p><span class="bolder">Keyword density:</span> {{ result.density|floatformat:2 }}%</p>
<h2>Averages across all sites:</h2>
{% if allresults.count > 0 %}
  <p><span class="bolder">Keyword count:</span> {{ keyword.average_count|floatformat:0 }}</p>
  <p><span class="bolder">Keyword density:</span> {{ keyword.average_density|floatformat:2 }}%</p>
  <p><span class="bolder">Number of sites used for average: {{ allresults.count }}</p>
  <p><em>* Excluding sites with 0 keyword count.</em></p>
  
  <h3>Keyword results:</h3>
  <table>
    <thead>
      <td>URL</td>
      <td>Word Count</td>
      <td>Density</td>
    </thead>
  {% for site in allresults %}
  <tr>
  <td>{{ site.url }}</td><td>{{ site.word_count }}</td><td>{{ site.density }}%</td>
  </tr>
  {% endfor %}
  </table>
{% else %}
  <p>No sites in database have non-zero keyword count.</p>
{% endif %}
<br>
{% else %}
<p>No results. Please make sure you entered a url and keyword.</p>
{% endif %}
<a class="btn" href="{% url 'crawl' %}">Go back</a>
{% endblock %}